# Generated by Django 3.0.2 on 2020-06-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200605_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
