# Generated by Django 3.0.2 on 2020-06-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
