# Generated by Django 3.0.2 on 2020-06-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20200610_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='overview',
        ),
    ]
