# Generated by Django 3.0.2 on 2020-06-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletterusers',
            new_name='Newsletteruser',
        ),
    ]
