# Generated by Django 3.0.2 on 2020-06-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0035_auto_20200614_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.ManyToManyField(to='newsletters.NewsletterUser'),
        ),
    ]
