# Generated by Django 3.0.2 on 2020-05-25 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('Tagname', models.CharField(choices=[('Movies', 'Movies'), ('Trailer', 'Trailer')], max_length=200)),
                ('cast', models.CharField(max_length=1000)),
                ('overview', models.TextField()),
                ('release_date', models.CharField(max_length=100)),
                ('runtime', models.CharField(max_length=100)),
                ('average_rating', models.FloatField()),
                ('thumbnail', models.ImageField(upload_to='image')),
                ('imdb', models.URLField(blank=True, max_length=500, null=True)),
                ('downloadlink', models.URLField(blank=True, max_length=800, null=True)),
                ('iframe', models.CharField(blank=True, max_length=1000, null=True)),
                ('Language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Language')),
                ('genre', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
