# Generated by Django 3.0.2 on 2020-06-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
