# Generated by Django 3.0.2 on 2020-05-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Tagname',
            field=models.CharField(choices=[('Movies', 'Movies'), ('Tvshows', 'Tvshows')], max_length=200),
        ),
    ]
