# Generated by Django 3.0.2 on 2020-06-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200613_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
