# Generated by Django 3.0.2 on 2020-05-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='average_rating',
            field=models.FloatField(default=9),
            preserve_default=False,
        ),
    ]
